### ISSUE TITLE
Failed to install due to termbox-sys library compile error

### ISSUE THREAD

**Issue by alphatroya** [fcsonline/tmux-thumbs#14]
My OS is Mac OS 10.15.1, rust version is 1.39.0

```
❯ cargo build --release
   Compiling termbox-sys v0.2.11
error: failed to run custom build command for `termbox-sys v0.2.11`

Caused by:
  process didn't exit successfully: `/Users/alphatroya/.tmux/plugins/tmux-thumbs/target/release/build/termbox-sys-5a3d19d67c0461d4/build-script-build` (exit code: 101)
--- stdout
running: "rm" "-rf" ".termbox"
running: "git" "clone" "https://github.com/nsf/termbox" ".termbox"
waf configure: setting CFLAGS to: `-m64 -fPIC`
running: "./waf" "configure" "--prefix=/"
Setting top to                           : /Users/alphatroya/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox
Setting out to                           : /Users/alphatroya/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/build
Checking for 'clang' (C compiler)        : /usr/bin/clang
'configure' finished successfully (0.177s)

--- stderr
Cloning into '.termbox'...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by fcsonline** [comment]
Is this a `tmux-thumbs` compile error or `termbox` issue? Could you check their repo, please?

**Comment by alphatroya** [comment]
I've restored compiled binary from the other machine, that resolved my issue. Maybe someone will run into similar issue but for me issue is solved, I close it. Thanks for help.

**Comment by rafi** [comment]
```sh
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.3
BuildVersion:   19D76

$ rustup update stable
info: syncing channel updates for 'stable-x86_64-apple-darwin'
  stable-x86_64-apple-darwin unchanged - rustc 1.41.0 (5e1a79984 2020-01-27)

$ cd ~/.config
$ git submodule add git://github.com/fcsonline/tmux-thumbs.git tmux/plugins/thumbs
$ cd tmux/plugins/thumbs

$ RUST_BACKTRACE=1 cargo build --release
   Compiling termbox-sys v0.2.11
   Compiling num-traits v0.1.43
   Compiling regex v1.3.1
   Compiling tempfile v3.1.0
   Compiling gag v0.1.10
error: failed to run custom build command for `termbox-sys v0.2.11`

Caused by:
  process didn't exit successfully: `/Users/rafi/.config/tmux/plugins/thumbs/target/release/build/termbox-sys-0021f08a9bfd9192/build-script-build` (exit code: 101)
--- stdout
running: "rm" "-rf" ".termbox"
running: "git" "clone" "https://github.com/nsf/termbox" ".termbox"
waf configure: setting CFLAGS to: `-m64 -fPIC`
running: "./waf" "configure" "--prefix=/"
Setting top to                           : /Users/rafi/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox
Setting out to                           : /Users/rafi/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/build
Checking for 'clang' (C compiler)        : /usr/bin/clang
'configure' finished successfully (0.104s)

--- stderr
Cloning into '.termbox'...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1188:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: build_script_build::run
  10: build_script_build::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```
